using System;
using System.Collections.Generic;
using UnityEngine;

namespace AFJK.Rapier.Samples
{
    /// <summary>
    /// Reimplements the Rapier 3D JavaScript demo catalog using the Unity <b>component</b> layer
    /// (<see cref="RapierWorldComponent"/>, <see cref="RapierRigidBodyComponent"/>, the collider /
    /// joint / character-controller / PID components) instead of the low-level <c>RapierWorld</c>
    /// API. Every body in every demo is a GameObject with Rapier components attached, so the same
    /// scenes could equally be authored by hand, generated by Scene Sync, or driven by a network
    /// bridge. The world is stepped manually each <see cref="FixedUpdate"/> so per-demo pre-step
    /// logic (fountain spawning, kinematic platform, character/PID control) can run first.
    /// </summary>
    public sealed class RapierComponentDemosSample : MonoBehaviour
    {
        private enum DemoKind
        {
            CollisionGroups,
            CharacterController,
            ConvexPolyhedron,
            Ccd,
            Damping,
            Fountain,
            Heightfield,
            Joints,
            KevaTower,
            LockedRotations,
            Platform,
            Pyramid,
            TriangleMesh,
            Voxels,
            PidController,
            GlbToTrimesh,
            GlbToConvexHull
        }

        [SerializeField] private DemoKind demo = DemoKind.Pyramid;
        [SerializeField] private float timestep = 1f / 60f;
        [SerializeField] private bool runOnStart = true;
        [SerializeField] private bool running = true;
        [SerializeField] private int maxFountainBodies = 400;

        private static readonly DemoKind[] DemoValues =
        {
            DemoKind.CollisionGroups,
            DemoKind.CharacterController,
            DemoKind.ConvexPolyhedron,
            DemoKind.Ccd,
            DemoKind.Damping,
            DemoKind.Fountain,
            DemoKind.GlbToConvexHull,
            DemoKind.GlbToTrimesh,
            DemoKind.Heightfield,
            DemoKind.Joints,
            DemoKind.KevaTower,
            DemoKind.LockedRotations,
            DemoKind.PidController,
            DemoKind.Platform,
            DemoKind.Pyramid,
            DemoKind.TriangleMesh,
            DemoKind.Voxels
        };

        private static readonly string[] DemoNames =
        {
            "collision groups",
            "character controller",
            "convex polyhedron",
            "CCD",
            "damping",
            "fountain",
            "GLB to convex hull",
            "GLB to trimesh",
            "heightfield",
            "joints",
            "keva tower",
            "locked rotations",
            "PID controller",
            "platform",
            "pyramid",
            "triangle mesh",
            "voxels"
        };

        private GameObject generatedRoot;
        private GameObject worldGo;
        private RapierWorldComponent worldComponent;
        private string status = "Not started.";
        private Vector2 demoScroll;
        private int selectedDemoIndex;
        private int tick;
        private ulong lastHash;
        private bool rebuildRequested;
        private int nextBodyId;
        private int fountainSpawnCounter;
        private bool debugDraw;
        private Material debugMaterial;
        private Vector3[] debugVertices;
        private Color[] debugColors;

        private readonly Queue<GameObject> fountainBodies = new Queue<GameObject>();

        // Platform demo state.
        private RapierRigidBodyComponent platformBody;
        private float platformPhase;

        // Character controller demo state.
        private RapierCharacterControllerComponent characterController;

        // PID controller demo state.
        private RapierRigidBodyComponent pidBody;
        private RapierPidControllerComponent pidController;

        private void Start()
        {
            selectedDemoIndex = IndexOf(demo);
            if (runOnStart)
            {
                BuildDemo();
            }
        }

        private void Update()
        {
            if (!rebuildRequested)
            {
                return;
            }

            rebuildRequested = false;
            BuildDemo();
        }

        private void FixedUpdate()
        {
            if (!running || worldComponent == null || worldComponent.World == null || !worldComponent.World.IsCreated)
            {
                return;
            }

            switch (demo)
            {
                case DemoKind.Fountain:
                    PreStepFountain();
                    break;
                case DemoKind.Platform:
                    PreStepPlatform();
                    break;
                case DemoKind.CharacterController:
                    PreStepCharacter();
                    break;
                case DemoKind.PidController:
                    PreStepPidController();
                    break;
            }

            // RapierWorldComponent.Step() runs the simulation and syncs every registered body's
            // GameObject transform from Rapier, so the components themselves drive the visuals.
            if (!worldComponent.Step())
            {
                running = false;
                status = $"Rapier step failed at tick {tick}.";
                Debug.LogError(status, this);
                return;
            }

            tick++;
            lastHash = worldComponent.StateHash();
            status = $"{DemoNames[selectedDemoIndex]} running. Tick {tick}, hash {lastHash:x16}.";
        }

        private void OnDisable()
        {
            DestroyGeneratedRoot();

            if (debugMaterial != null)
            {
                DestroyImmediate(debugMaterial);
                debugMaterial = null;
            }
        }

        private void OnRenderObject()
        {
            if (!debugDraw || worldComponent == null || worldComponent.World == null || !worldComponent.World.IsCreated)
            {
                return;
            }

            const int maxLines = 8192;
            if (debugColors == null || debugColors.Length < maxLines)
            {
                debugColors = new Color[maxLines];
            }

            if (debugVertices == null || debugVertices.Length < maxLines * 2)
            {
                debugVertices = new Vector3[maxLines * 2];
            }

            var lines = worldComponent.World.DebugRender(debugVertices, debugColors);
            if (lines <= 0)
            {
                return;
            }

            EnsureDebugMaterial();
            debugMaterial.SetPass(0);
            GL.PushMatrix();
            GL.Begin(GL.LINES);
            for (var i = 0; i < lines; i++)
            {
                GL.Color(debugColors[i]);
                GL.Vertex(debugVertices[i * 2]);
                GL.Vertex(debugVertices[(i * 2) + 1]);
            }

            GL.End();
            GL.PopMatrix();
        }

        private void EnsureDebugMaterial()
        {
            if (debugMaterial != null)
            {
                return;
            }

            var shader = Shader.Find("Hidden/Internal-Colored");
            debugMaterial = new Material(shader) { hideFlags = HideFlags.HideAndDontSave };
            debugMaterial.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
            debugMaterial.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
            debugMaterial.SetInt("_Cull", (int)UnityEngine.Rendering.CullMode.Off);
            debugMaterial.SetInt("_ZWrite", 0);
            debugMaterial.SetInt("_ZTest", (int)UnityEngine.Rendering.CompareFunction.Always);
        }

        private void OnGUI()
        {
            var areaHeight = Mathf.Min(Screen.height - 24f, 560f);
            GUILayout.BeginArea(new Rect(12f, 12f, 520f, areaHeight), GUI.skin.window);
            GUILayout.Label("Rapier JS 3D Demos — Unity Component Layer");
            GUILayout.Label(status);
            GUILayout.Label($"Tick: {tick}  Hash: {lastHash:x16}");

            demoScroll = GUILayout.BeginScrollView(demoScroll);
            var nextIndex = GUILayout.SelectionGrid(selectedDemoIndex, DemoNames, 2);
            GUILayout.EndScrollView();
            if (nextIndex != selectedDemoIndex)
            {
                selectedDemoIndex = nextIndex;
                demo = DemoValues[selectedDemoIndex];
                RequestRebuild();
            }

            GUILayout.BeginHorizontal();
            if (GUILayout.Button(running ? "Pause" : "Run"))
            {
                running = !running;
            }

            if (GUILayout.Button("Restart"))
            {
                RequestRebuild();
            }
            GUILayout.EndHorizontal();

            debugDraw = GUILayout.Toggle(debugDraw, " Debug draw colliders");

            GUILayout.Label("Each body is a GameObject with Rapier components attached.");
            GUILayout.EndArea();
        }

        private void RequestRebuild()
        {
            status = "Rebuild requested.";
            rebuildRequested = true;
        }

        private void BuildDemo()
        {
            DestroyGeneratedRoot();
            fountainBodies.Clear();
            tick = 0;
            lastHash = 0;
            nextBodyId = 0;
            fountainSpawnCounter = 0;
            platformBody = null;
            platformPhase = 0f;
            characterController = null;
            pidBody = null;
            pidController = null;

            if (!TryProbeNative(out var nativeError))
            {
                running = false;
                status = nativeError;
                Debug.LogWarning(nativeError, this);
                return;
            }

            generatedRoot = new GameObject("Generated Rapier Component Demo");
            EnsureCameraAndLight();

            try
            {
                switch (demo)
                {
                    case DemoKind.Ccd:
                        BuildCcd();
                        break;
                    case DemoKind.Damping:
                        BuildDamping();
                        break;
                    case DemoKind.Fountain:
                        BuildFountain();
                        break;
                    case DemoKind.GlbToTrimesh:
                        BuildGlbToTrimesh();
                        break;
                    case DemoKind.GlbToConvexHull:
                        BuildGlbToConvexHull();
                        break;
                    case DemoKind.KevaTower:
                        BuildKevaTower();
                        break;
                    case DemoKind.Pyramid:
                        BuildPyramid();
                        break;
                    case DemoKind.CollisionGroups:
                        BuildCollisionGroups();
                        break;
                    case DemoKind.Joints:
                        BuildJoints();
                        break;
                    case DemoKind.Platform:
                        BuildPlatform();
                        break;
                    case DemoKind.LockedRotations:
                        BuildLockedRotations();
                        break;
                    case DemoKind.ConvexPolyhedron:
                        BuildConvexPolyhedron();
                        break;
                    case DemoKind.TriangleMesh:
                        BuildTriangleMesh();
                        break;
                    case DemoKind.Heightfield:
                        BuildHeightfield();
                        break;
                    case DemoKind.Voxels:
                        BuildVoxels();
                        break;
                    case DemoKind.CharacterController:
                        BuildCharacterController();
                        break;
                    case DemoKind.PidController:
                        BuildPidController();
                        break;
                    default:
                        running = false;
                        status = $"{DemoNames[selectedDemoIndex]} is not wired up.";
                        return;
                }

                running = true;
                status = $"{DemoNames[selectedDemoIndex]} loaded with Rapier components.";
            }
            catch (Exception ex) when (IsNativeLoadFailure(ex))
            {
                DestroyGeneratedRoot();
                running = false;
                status = "Rapier native plugin is not available. Build and copy rapier_unity_ffi for this platform.";
                Debug.LogWarning($"{status}\n{ex}", this);
            }
        }

        // ---- Demos -------------------------------------------------------------------------

        private void BuildPyramid()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("floor", RapierRigidBodyType.Fixed, new Vector3(0f, -0.1f, 0f), Quaternion.identity, new Vector3(30f, 0.1f, 30f), 0f, ColorFor("floor"));

            const float spacing = 1.25f;
            for (var layer = 0; layer < 10; layer++)
            {
                for (var row = layer; row < 10; row++)
                {
                    for (var col = layer; col < 10; col++)
                    {
                        var position = new Vector3(
                            layer * spacing / 2f + (col - layer) * spacing - 10f,
                            layer * spacing + 10f,
                            layer * spacing / 2f + (row - layer) * spacing - 10f);
                        CreateBox(NextId("pyramid-box"), RapierRigidBodyType.Dynamic, position, Quaternion.identity, Vector3.one * 0.5f, 1f, ColorFor("box"));
                    }
                }
            }

            LookAt(new Vector3(-32f, 20f, -28f), Vector3.zero);
        }

        private void BuildKevaTower()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("floor", RapierRigidBodyType.Fixed, new Vector3(0f, -0.1f, 0f), Quaternion.identity, new Vector3(50f, 0.1f, 50f), 0f, ColorFor("floor"));

            var block = new Vector3(0.1f, 0.5f, 2f);
            var columnsByTier = new[] { 0, 3, 5, 5, 7, 9 };
            var currentY = 0f;

            for (var tier = 5; tier >= 1; tier--)
            {
                var columns = columnsByTier[tier];
                var span = tier * block.z * 2f;
                CreateKevaStack(block, new Vector3(-span / 2f, currentY, -span / 2f), tier, columns, 3 * tier + 1);
                currentY += columns * block.y * 2f + 2f * block.x;
            }

            LookAt(new Vector3(-70f, 18f, 29f), new Vector3(0.6f, 3.1f, -0.3f));
        }

        private void CreateKevaStack(Vector3 block, Vector3 origin, int rows, int columns, int depth)
        {
            var countA = rows;
            var countB = depth;
            var span = 2f * block.z * rows;
            var height = 2f * block.y * columns;
            var pitch = (block.z * rows - block.x) / Mathf.Max(1, depth - 1);
            var shapes = new[]
            {
                block,
                new Vector3(block.z, block.y, block.x)
            };

            for (var layer = 0; layer < columns; layer++)
            {
                var swapped = countA;
                countA = countB;
                countB = swapped;

                var halfExtents = shapes[layer % 2];
                var layerY = halfExtents.y * layer * 2f;

                for (var a = 0; a < countA; a++)
                {
                    var x = layer % 2 == 0 ? pitch * a * 2f : halfExtents.x * a * 2f;
                    for (var b = 0; b < countB; b++)
                    {
                        var z = layer % 2 == 0 ? halfExtents.z * b * 2f : pitch * b * 2f;
                        var position = new Vector3(x + halfExtents.x + origin.x, layerY + halfExtents.y + origin.y, z + halfExtents.z + origin.z);
                        CreateBox(NextId("keva"), RapierRigidBodyType.Dynamic, position, Quaternion.identity, halfExtents, 1f, ColorFor("keva"));
                    }
                }
            }

            var cap = new Vector3(block.z, block.x, block.y);
            for (var x = 0; x < span / (2f * cap.x); x++)
            {
                for (var z = 0; z < span / (2f * cap.z); z++)
                {
                    var position = new Vector3(x * cap.x * 2f + cap.x + origin.x, cap.y + origin.y + height, z * cap.z * 2f + cap.z + origin.z);
                    CreateBox(NextId("keva-cap"), RapierRigidBodyType.Dynamic, position, Quaternion.identity, cap, 1f, ColorFor("keva"));
                }
            }
        }

        private void BuildDamping()
        {
            CreateWorld(Vector3.zero);

            const float fraction = 0.1f;
            for (var i = 0; i < 10; i++)
            {
                var sin = Mathf.Sin(i * fraction * Mathf.PI * 2f);
                var cos = Mathf.Cos(i * fraction * Mathf.PI * 2f);
                CreateBox(
                    NextId("damping-box"),
                    RapierRigidBodyType.Dynamic,
                    new Vector3(sin, cos, 0f),
                    Quaternion.identity,
                    Vector3.one * 0.2f,
                    1f,
                    ColorFor("box"),
                    new Vector3(10f * sin, 10f * cos, 0f),
                    new Vector3(0f, 0f, 100f),
                    (i + 1) * fraction * 10f,
                    (10 - i) * fraction * 10f);
            }

            LookAt(new Vector3(0f, 2f, 20f), new Vector3(0f, 2f, 0f));
        }

        private void BuildCcd()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("floor", RapierRigidBodyType.Fixed, new Vector3(0f, -0.1f, 0f), Quaternion.identity, new Vector3(30f, 0.1f, 30f), 0f, ColorFor("floor"));

            for (var wall = 0; wall < 5; wall++)
            {
                CreateCcdWall(new Vector3(6f * wall, 0.6f, 0f), 8);
            }

            CreateSphere(
                "ccd-ball",
                RapierRigidBodyType.Dynamic,
                new Vector3(-20f, 2.6f, 0f),
                1f,
                10f,
                ColorFor("sphere"),
                new Vector3(1000f, 0f, 0f),
                Vector3.zero,
                0f,
                0f,
                true);

            LookAt(new Vector3(-32f, 20f, -28f), Vector3.zero);
        }

        private void CreateCcdWall(Vector3 origin, int count)
        {
            for (var row = 0; row < count; row++)
            {
                for (var col = row; col < count; col++)
                {
                    var position = new Vector3(origin.x, origin.y + row, origin.z + 2f * col - row - count);
                    CreateBox(NextId("ccd-wall"), RapierRigidBodyType.Dynamic, position, Quaternion.identity, new Vector3(0.5f, 0.5f, 1f), 1f, ColorFor("box"));
                }
            }
        }

        private void BuildFountain()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("floor", RapierRigidBodyType.Fixed, Vector3.zero, Quaternion.identity, new Vector3(40f, 0.1f, 40f), 0f, ColorFor("floor"));
            LookAt(new Vector3(-88f, 47f, 84f), new Vector3(0f, 10f, 0f));
        }

        private void PreStepFountain()
        {
            const int spawnInterval = 5;
            var position = new Vector3(0f, 10f, 0f);
            var velocity = new Vector3(0f, 15f, 0f);

            fountainSpawnCounter++;
            if (fountainSpawnCounter % spawnInterval != 0)
            {
                return;
            }

            var shapeIndex = (fountainSpawnCounter / spawnInterval) % 4;
            RapierRigidBodyComponent body;
            switch (shapeIndex)
            {
                case 0:
                    body = CreateBox(NextId("fountain-box"), RapierRigidBodyType.Dynamic, position, Quaternion.identity, Vector3.one, 1f, ColorFor("box"), velocity);
                    break;
                case 1:
                    body = CreateSphere(NextId("fountain-sphere"), RapierRigidBodyType.Dynamic, position, 1f, 1f, ColorFor("sphere"), velocity, Vector3.zero, 0f, 0f, false);
                    break;
                case 2:
                    body = CreateConvexCylinderBody(NextId("fountain-cylinder"), position, 1f, ColorFor("capsule"), velocity);
                    break;
                default:
                    body = CreateConvexConeBody(NextId("fountain-cone"), position, 1f, ColorFor("keva"), velocity);
                    break;
            }

            fountainBodies.Enqueue(body.gameObject);
            while (fountainBodies.Count > Mathf.Max(1, maxFountainBodies))
            {
                var oldest = fountainBodies.Dequeue();
                if (oldest != null)
                {
                    Destroy(oldest);
                }
            }
        }

        private void BuildGlbToTrimesh()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("glb-ground", RapierRigidBodyType.Fixed, Vector3.zero, Quaternion.identity, new Vector3(5f, 0.1f, 5f), 0f, ColorFor("floor"));

            var vertices = RapierComponentDemosSuzanneMesh.CreateVertices();
            var indices = RapierComponentDemosSuzanneMesh.CreateIndices();
            CreateTrimeshGround("glb-trimesh-suzanne", vertices, indices, ColorFor("keva"));

            LookAt(new Vector3(10f, 5f, 10f), Vector3.zero);
        }

        private void BuildGlbToConvexHull()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("glb-convex-ground", RapierRigidBodyType.Fixed, Vector3.zero, Quaternion.identity, new Vector3(5f, 0.1f, 5f), 0f, ColorFor("floor"));

            var vertices = RapierComponentDemosSuzanneMesh.CreateVertices();
            var indices = RapierComponentDemosSuzanneMesh.CreateIndices();
            CreateConvexHullStatic("glb-convex-suzanne", vertices, vertices, indices, ColorFor("keva"));

            LookAt(new Vector3(10f, 5f, 10f), Vector3.zero);
        }

        private void BuildCollisionGroups()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateCollisionGroupsGround();

            var color1 = new Color(0.37f, 0.73f, 0.38f);
            var color2 = new Color(0.16f, 0.52f, 0.92f);

            const int count = 8;
            const float radius = 0.1f;
            const int layers = 4;
            var shift = radius * 2f;
            var center = shift * (count / 2f);

            for (var layer = 0; layer < layers; layer++)
            {
                for (var xIndex = 0; xIndex < count; xIndex++)
                {
                    for (var zIndex = 0; zIndex < count; zIndex++)
                    {
                        var even = zIndex % 2 == 0;
                        var color = even ? color1 : color2;
                        var position = new Vector3(
                            xIndex * shift - center,
                            layer * shift + 2.5f,
                            zIndex * shift - center);

                        var box = CreateBox(
                            NextId("group-box"),
                            RapierRigidBodyType.Dynamic,
                            position,
                            Quaternion.identity,
                            Vector3.one * radius,
                            1f,
                            color);
                        var groupBit = even ? (ushort)0x0001 : (ushort)0x0002;
                        GetCollider<RapierBoxCollider>(box).SetAuthoredCollisionGroups(groupBit, groupBit);
                    }
                }
            }

            LookAt(new Vector3(10f, 5f, 10f), Vector3.zero);
        }

        private void CreateCollisionGroupsGround()
        {
            var go = NewBodyObject("collision-groups-ground", Vector3.zero, Quaternion.identity);
            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, RapierRigidBodyType.Fixed, Vector3.zero, Vector3.zero, 0f, 0f, false);

            AddBoxCollider(go, new Vector3(5f, 0.1f, 5f), Vector3.zero, 0f, 0xFFFF, 0xFFFF);
            AddBoxCollider(go, new Vector3(1f, 0.1f, 1f), new Vector3(0f, 1f, 0f), 0f, 0x0001, 0x0001);
            AddBoxCollider(go, new Vector3(1f, 0.1f, 1f), new Vector3(0f, 2f, 0f), 0f, 0x0002, 0x0002);

            CreateBoxVisualChild(go, "floor", new Vector3(5f, 0.1f, 5f), Vector3.zero, ColorFor("floor"));
            CreateBoxVisualChild(go, "floor-1", new Vector3(1f, 0.1f, 1f), new Vector3(0f, 1f, 0f), new Color(0.37f, 0.73f, 0.38f));
            CreateBoxVisualChild(go, "floor-2", new Vector3(1f, 0.1f, 1f), new Vector3(0f, 2f, 0f), new Color(0.16f, 0.52f, 0.92f));

            go.SetActive(true);
        }

        private void BuildJoints()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreatePrismaticJointChain(new Vector3(20f, 10f, 0f), 5);
            CreateFixedJointGrid(new Vector3(0f, 10f, 0f), 5);
            CreateRevoluteJointChain(new Vector3(20f, 0f, 0f), 3);
            CreateSphericalJointGrid(15);

            LookAt(new Vector3(15f, 5f, 42f), new Vector3(13f, 1f, 1f));
        }

        private void CreatePrismaticJointChain(Vector3 origin, int count)
        {
            const float radius = 0.4f;
            const float shift = 1.0f;

            var parent = CreateBox(NextId("prismatic-anchor"), RapierRigidBodyType.Fixed, origin, Quaternion.identity, Vector3.one * radius, 0f, ColorFor("floor"));

            for (var i = 0; i < count; i++)
            {
                var position = new Vector3(origin.x, origin.y, origin.z + (i + 1) * shift);
                var child = CreateBox(NextId("prismatic-link"), RapierRigidBodyType.Dynamic, position, Quaternion.identity, Vector3.one * radius, 1f, ColorFor("box"));
                var axis = i % 2 == 0 ? new Vector3(1f, 1f, 0f) : new Vector3(-1f, 1f, 0f);
                var joint = AddJoint<RapierPrismaticJointComponent>(parent, child, Vector3.zero, new Vector3(0f, 0f, -shift));
                joint.Axis = axis;
                joint.gameObject.SetActive(true);
                joint.SetLimits(RapierJointAxis.LinearX, -2f, 2f);
                parent = child;
            }
        }

        private void CreateRevoluteJointChain(Vector3 origin, int count)
        {
            const float radius = 0.4f;
            const float shift = 2.0f;

            var parent = CreateBox(NextId("revolute-anchor"), RapierRigidBodyType.Fixed, new Vector3(origin.x, origin.y, 0f), Quaternion.identity, Vector3.one * radius, 0f, ColorFor("floor"));

            for (var i = 0; i < count; i++)
            {
                var z = origin.z + i * shift * 2f + shift;
                var positions = new[]
                {
                    new Vector3(origin.x, origin.y, z),
                    new Vector3(origin.x + shift, origin.y, z),
                    new Vector3(origin.x + shift, origin.y, z + shift),
                    new Vector3(origin.x, origin.y, z + shift)
                };

                var links = new RapierRigidBodyComponent[4];
                for (var k = 0; k < links.Length; k++)
                {
                    links[k] = CreateBox(NextId("revolute-link"), RapierRigidBodyType.Dynamic, positions[k], Quaternion.identity, Vector3.one * radius, 1f, ColorFor("box"));
                }

                CreateRevolute(parent, links[0], Vector3.zero, new Vector3(0f, 0f, -shift), Vector3.forward);
                CreateRevolute(links[0], links[1], Vector3.zero, new Vector3(-shift, 0f, 0f), Vector3.right);
                CreateRevolute(links[1], links[2], Vector3.zero, new Vector3(0f, 0f, -shift), Vector3.forward);
                CreateRevolute(links[2], links[3], Vector3.zero, new Vector3(shift, 0f, 0f), Vector3.right);
                parent = links[3];
            }
        }

        private void CreateRevolute(RapierRigidBodyComponent a, RapierRigidBodyComponent b, Vector3 anchor1, Vector3 anchor2, Vector3 axis)
        {
            var joint = AddJoint<RapierRevoluteJointComponent>(a, b, anchor1, anchor2);
            joint.Axis = axis;
            joint.gameObject.SetActive(true);
        }

        private void CreateFixedJointGrid(Vector3 origin, int count)
        {
            const float radius = 0.4f;
            const float shift = 1.0f;
            var parents = new List<RapierRigidBodyComponent>(count * count);

            for (var k = 0; k < count; k++)
            {
                for (var i = 0; i < count; i++)
                {
                    var fixedBody = i == 0 && ((k % 4 == 0 && k != count - 2) || k == count - 1);
                    var child = CreateSphere(
                        NextId("fixed-joint-node"),
                        fixedBody ? RapierRigidBodyType.Fixed : RapierRigidBodyType.Dynamic,
                        new Vector3(origin.x + k * shift, origin.y, origin.z + i * shift),
                        radius,
                        fixedBody ? 0f : 1f,
                        fixedBody ? ColorFor("floor") : ColorFor("sphere"),
                        Vector3.zero,
                        Vector3.zero,
                        0f,
                        0f,
                        false);

                    if (i > 0)
                    {
                        AddJoint<RapierFixedJointComponent>(parents[parents.Count - 1], child, Vector3.zero, new Vector3(0f, 0f, -shift)).gameObject.SetActive(true);
                    }

                    if (k > 0)
                    {
                        AddJoint<RapierFixedJointComponent>(parents[parents.Count - count], child, Vector3.zero, new Vector3(-shift, 0f, 0f)).gameObject.SetActive(true);
                    }

                    parents.Add(child);
                }
            }
        }

        private void CreateSphericalJointGrid(int count)
        {
            const float radius = 0.4f;
            const float shift = 1.0f;
            var parents = new List<RapierRigidBodyComponent>(count * count);

            for (var k = 0; k < count; k++)
            {
                for (var i = 0; i < count; i++)
                {
                    var fixedBody = i == 0 && (k % 4 == 0 || k == count - 1);
                    var child = CreateSphere(
                        NextId("spherical-joint-node"),
                        fixedBody ? RapierRigidBodyType.Fixed : RapierRigidBodyType.Dynamic,
                        new Vector3(k * shift, 0f, i * shift),
                        radius,
                        fixedBody ? 0f : 1f,
                        fixedBody ? ColorFor("floor") : ColorFor("sphere"),
                        Vector3.zero,
                        Vector3.zero,
                        0f,
                        0f,
                        false);

                    if (i > 0)
                    {
                        AddJoint<RapierSphericalJointComponent>(parents[parents.Count - 1], child, Vector3.zero, new Vector3(0f, 0f, -shift)).gameObject.SetActive(true);
                    }

                    if (k > 0)
                    {
                        AddJoint<RapierSphericalJointComponent>(parents[parents.Count - count], child, Vector3.zero, new Vector3(-shift, 0f, 0f)).gameObject.SetActive(true);
                    }

                    parents.Add(child);
                }
            }
        }

        private void BuildPlatform()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));

            BuildPlatformMesh(out var vertices, out var indices, 20, 70f, 4f, 70f);
            platformBody = CreateTrimeshBody("platform-trimesh", RapierRigidBodyType.KinematicVelocityBased, vertices, indices, ColorFor("floor"));
            platformPhase = 0f;

            CreateStackedShapeGrid("platform-body", 4, 10, 1f, 3f);

            LookAt(new Vector3(-88.48024f, 46.91133f, 83.56055f), Vector3.zero);
        }

        private void PreStepPlatform()
        {
            if (platformBody == null || !platformBody.IsRegistered)
            {
                return;
            }

            platformPhase += 0.016f;
            platformBody.SetLinearVelocity(new Vector3(0f, Mathf.Sin(platformPhase) * 10f, 0f));
            platformBody.SetAngularVelocity(new Vector3(0f, Mathf.Sin(platformPhase) * 0.2f, 0f));
        }

        private void BuildLockedRotations()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            const float groundHeight = 0.1f;
            CreateBox("floor", RapierRigidBodyType.Fixed, new Vector3(0f, -groundHeight, 0f), Quaternion.identity, new Vector3(1.7f, groundHeight, 1.7f), 0f, ColorFor("floor"));

            var xRotor = CreateBox("locked-x-rotor", RapierRigidBodyType.Dynamic, new Vector3(0f, 3f, 0f), Quaternion.identity, new Vector3(0.2f, 0.6f, 2f), 1f, ColorFor("box"));
            xRotor.SetEnabledTranslations(false, false, false);
            xRotor.SetEnabledRotations(true, false, false);

            var lockedCylinder = CreateConvexCylinderBody("locked-cylinder", new Vector3(0.2f, 5f, 0.4f), 0.4f, ColorFor("capsule"), Vector3.zero, 0.6f);
            lockedCylinder.SetEnabledRotations(false, false, false);

            LookAt(new Vector3(-10f, 3f, 0f), new Vector3(0f, 3f, 0f));
        }

        private void BuildConvexPolyhedron()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            BuildPlatformMesh(out var vertices, out var indices, 20, 40f, 4f, 40f);
            CreateTrimeshBody("convex-ground", RapierRigidBodyType.Fixed, vertices, indices, ColorFor("floor"));

            const int columns = 5;
            const int layers = 15;
            const float scale = 2f;
            const float borderRadius = 0.1f;
            var shift = borderRadius * 2f + scale;
            var centerX = shift * (columns / 2f);
            var centerY = shift * 0.5f;
            var centerZ = shift * (columns / 2f);
            var randomState = 0x636f6e76u;

            for (var layer = 0; layer < layers; layer++)
            {
                for (var xIndex = 0; xIndex < columns; xIndex++)
                {
                    for (var zIndex = 0; zIndex < columns; zIndex++)
                    {
                        var position = new Vector3(
                            xIndex * shift - centerX,
                            layer * shift + centerY + 3f,
                            zIndex * shift - centerZ);
                        var points = RandomConvexPoints(ref randomState, 10, scale);
                        CreateConvexBody(NextId("convex"), position, points, ColorFor("sphere"), scale * 0.5f);
                    }
                }
            }

            LookAt(new Vector3(-88.48024f, 46.91133f, 83.56055f), Vector3.zero);
        }

        private void BuildTriangleMesh()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            BuildPlatformMesh(out var vertices, out var indices, 20, 70f, 4f, 70f);
            CreateTrimeshBody("trimesh-ground", RapierRigidBodyType.Fixed, vertices, indices, ColorFor("floor"));

            CreateStackedShapeGrid("trimesh-body", 4, 10, 1f, 3f);

            LookAt(new Vector3(-88.48024f, 46.91133f, 83.56055f), Vector3.zero);
        }

        private void BuildHeightfield()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));

            const int subdivisions = 20;
            var samples = subdivisions + 1;
            var heights = new float[samples * samples];
            var randomState = 0x68656967u;
            for (var i = 0; i < heights.Length; i++)
            {
                heights[i] = NextPlatformRandom(ref randomState);
            }

            var scale = new Vector3(70f, 4f, 70f);
            CreateHeightfieldGround("heightfield-ground", heights, samples, samples, scale, ColorFor("keva"));

            CreateStackedShapeGrid("heightfield-body", 4, 10, 1f, 3f);

            LookAt(new Vector3(-88.48024f, 46.91133f, 83.56055f), Vector3.zero);
        }

        private void BuildVoxels()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));

            var voxelSize = new Vector3(1f, 1.2f, 1.5f);
            var points = GenerateVoxelPoints(100);
            CreateVoxelsGround("voxels-ground", points, voxelSize, ColorFor("floor"));

            CreateStackedShapeGrid("voxels-body", 10, 4, 1f, 10f);

            LookAt(new Vector3(-88.48024f, 46.91133f, 83.56055f), Vector3.zero);
        }

        private void BuildCharacterController()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("floor", RapierRigidBodyType.Fixed, Vector3.zero, Quaternion.identity, new Vector3(15f, 0.1f, 15f), 0f, ColorFor("floor"));
            CreateControlBlocks("character-block");

            const float halfHeight = 1.2f;
            const float radius = 0.6f;
            var characterBody = CreateCapsule("character", RapierRigidBodyType.KinematicPositionBased, new Vector3(-10f, 4f, -10f), halfHeight, radius, 1f, ColorFor("capsule"), Vector3.zero);

            characterController = characterBody.gameObject.AddComponent<RapierCharacterControllerComponent>();
            characterController.RigidBody = characterBody;
            characterController.ShapeType = RapierShapeType.Capsule;
            characterController.HalfHeight = halfHeight;
            characterController.Radius = radius;
            characterController.Controller = BuildCharacterControllerSettings();
            characterController.ExcludeOwnBody = true;

            LookAt(new Vector3(-40f, 19.73f, 0f), new Vector3(0f, -0.4126f, 0f));
        }

        private static RapierCharacterController BuildCharacterControllerSettings()
        {
            var controller = RapierCharacterController.Default;
            controller.AutostepEnabled = true;
            controller.AutostepMaxHeight = 0.7f;
            controller.AutostepMinWidth = 0.3f;
            controller.AutostepIncludeDynamicBodies = true;
            controller.SnapToGroundEnabled = true;
            controller.SnapToGroundDistance = 0.7f;
            return controller;
        }

        private void PreStepCharacter()
        {
            if (characterController == null)
            {
                return;
            }

            const float speed = 0.2f;
            var desired = new Vector3(0f, Input.GetKey(KeyCode.Space) ? speed : -speed, 0f);

            if (Input.GetKey(KeyCode.UpArrow))
            {
                desired.x = speed;
            }
            else if (Input.GetKey(KeyCode.DownArrow))
            {
                desired.x = -speed;
            }

            if (Input.GetKey(KeyCode.LeftArrow))
            {
                desired.z = -speed;
            }
            else if (Input.GetKey(KeyCode.RightArrow))
            {
                desired.z = speed;
            }

            characterController.Move(desired, Mathf.Max(0.0001f, timestep));
        }

        private void BuildPidController()
        {
            CreateWorld(new Vector3(0f, -9.81f, 0f));
            CreateBox("floor", RapierRigidBodyType.Fixed, Vector3.zero, Quaternion.identity, new Vector3(15f, 0.1f, 15f), 0f, ColorFor("floor"));
            CreateControlBlocks("pid-block");

            pidBody = CreateConvexCylinderBody("pid-character", new Vector3(-10f, 4f, -10f), 0.6f, ColorFor("capsule"), Vector3.zero, 1.2f);
            pidBody.SetGravityScale(10f);
            pidBody.SetSoftCcdPrediction(10f);

            pidController = pidBody.gameObject.AddComponent<RapierPidControllerComponent>();
            pidController.RigidBody = pidBody;
            pidController.Kp = 60f;
            pidController.Ki = 0f;
            pidController.Kd = 1f;
            pidController.Axes = RapierPidAxesMask.AllAng;

            LookAt(new Vector3(-40f, 19.73f, 0f), new Vector3(0f, -0.4126f, 0f));
        }

        private void PreStepPidController()
        {
            if (pidBody == null || !pidBody.IsRegistered || pidController == null)
            {
                return;
            }

            const float speed = 0.2f;
            var dir = Vector3.zero;

            if (Input.GetKey(KeyCode.UpArrow))
            {
                dir.x = speed;
            }
            else if (Input.GetKey(KeyCode.DownArrow))
            {
                dir.x = -speed;
            }

            if (Input.GetKey(KeyCode.LeftArrow))
            {
                dir.z = -speed;
            }
            else if (Input.GetKey(KeyCode.RightArrow))
            {
                dir.z = speed;
            }

            if (Input.GetKey(KeyCode.Space))
            {
                dir.y = speed;
            }

            if (dir == Vector3.zero)
            {
                pidController.Axes = RapierPidAxesMask.AllAng;
            }
            else if (Mathf.Approximately(dir.y, 0f))
            {
                pidController.Axes = RapierPidAxesMask.AllAng | RapierPidAxesMask.LinX | RapierPidAxesMask.LinZ;
            }
            else
            {
                pidController.Axes = RapierPidAxesMask.All;
            }

            if (!pidBody.TryGetTransform(out var current))
            {
                return;
            }

            pidController.ApplyLinearCorrection(current.Position + dir, Vector3.zero);
            pidController.ApplyAngularCorrection(Quaternion.identity, Vector3.zero);
        }

        // Shared block grid used by the character-controller and PID demos.
        private void CreateControlBlocks(string idPrefix)
        {
            const float radius = 0.5f;
            const int count = 5;
            var shift = radius * 2.5f;
            var center = count * radius;
            const float height = 5f;

            for (var layer = 0; layer < count; layer++)
            {
                for (var row = layer; row < count; row++)
                {
                    for (var column = layer; column < count; column++)
                    {
                        var position = new Vector3(
                            layer * shift * 0.5f + (column - layer) * shift - center,
                            layer * shift * 0.5f + height,
                            layer * shift * 0.5f + (row - layer) * shift - center);
                        CreateBox(NextId(idPrefix), RapierRigidBodyType.Dynamic, position, Quaternion.identity, new Vector3(radius, radius * 0.5f, radius), 1f, ColorFor("box"));
                    }
                }
            }
        }

        private void CreateStackedShapeGrid(string idPrefix, int columns, int layers, float radius, float baseHeight)
        {
            var shift = radius * 3f;
            var centerY = shift * 0.5f;
            var offset = -columns * shift * 0.5f;

            for (var layer = 0; layer < layers; layer++)
            {
                for (var xIndex = 0; xIndex < columns; xIndex++)
                {
                    for (var zIndex = 0; zIndex < columns; zIndex++)
                    {
                        var position = new Vector3(
                            xIndex * shift + offset,
                            layer * shift + centerY + baseHeight,
                            zIndex * shift + offset);
                        CreateStackBody(NextId(idPrefix), layer % 5, position, radius);
                    }
                }

                offset -= 0.05f * radius * (columns - 1f);
            }
        }

        private RapierRigidBodyComponent CreateStackBody(string id, int shapeKind, Vector3 position, float radius)
        {
            switch (shapeKind)
            {
                case 0:
                    return CreateBox(id, RapierRigidBodyType.Dynamic, position, Quaternion.identity, Vector3.one * radius, 1f, ColorFor("box"));
                case 1:
                    return CreateSphere(id, RapierRigidBodyType.Dynamic, position, radius, 1f, ColorFor("sphere"), Vector3.zero, Vector3.zero, 0f, 0f, false);
                case 2:
                    return CreateConvexCylinderBody(id, position, radius, ColorFor("capsule"), Vector3.zero);
                case 3:
                    return CreateConvexConeBody(id, position, radius, ColorFor("keva"), Vector3.zero);
                default:
                    return CreateCompoundBody(id, position, radius);
            }
        }

        // ---- Component body builders -------------------------------------------------------

        private RapierRigidBodyComponent CreateBox(
            string id,
            RapierRigidBodyType bodyType,
            Vector3 position,
            Quaternion rotation,
            Vector3 halfExtents,
            float density,
            Color color,
            Vector3 linearVelocity = default,
            Vector3 angularVelocity = default,
            float linearDamping = 0f,
            float angularDamping = 0f)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
            ConfigureVisual(go, id, position, rotation, halfExtents * 2f, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, bodyType, linearVelocity, angularVelocity, linearDamping, angularDamping, false);

            var collider = go.AddComponent<RapierBoxCollider>();
            collider.HalfExtents = halfExtents;
            collider.Density = density;

            go.SetActive(true);
            return body;
        }

        private RapierRigidBodyComponent CreateSphere(
            string id,
            RapierRigidBodyType bodyType,
            Vector3 position,
            float radius,
            float density,
            Color color,
            Vector3 linearVelocity,
            Vector3 angularVelocity,
            float linearDamping,
            float angularDamping,
            bool ccd)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            ConfigureVisual(go, id, position, Quaternion.identity, Vector3.one * radius * 2f, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, bodyType, linearVelocity, angularVelocity, linearDamping, angularDamping, ccd);

            var collider = go.AddComponent<RapierSphereCollider>();
            collider.Radius = radius;
            collider.Density = density;

            go.SetActive(true);
            return body;
        }

        private RapierRigidBodyComponent CreateCapsule(
            string id,
            RapierRigidBodyType bodyType,
            Vector3 position,
            float halfHeight,
            float radius,
            float density,
            Color color,
            Vector3 linearVelocity)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Capsule);
            var totalHeight = halfHeight * 2f + radius * 2f;
            ConfigureVisual(go, id, position, Quaternion.identity, new Vector3(radius * 2f, totalHeight / 2f, radius * 2f), color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, bodyType, linearVelocity, Vector3.zero, 0f, 0f, false);

            var collider = go.AddComponent<RapierCapsuleCollider>();
            collider.HalfHeight = halfHeight;
            collider.Radius = radius;
            collider.Density = density;

            go.SetActive(true);
            return body;
        }

        private RapierRigidBodyComponent CreateConvexCylinderBody(string id, Vector3 position, float radius, Color color, Vector3 linearVelocity, float halfHeight = -1f)
        {
            const int segments = 16;
            var cylinderHalfHeight = halfHeight > 0f ? halfHeight : radius;
            BuildCylinderMesh(cylinderHalfHeight, radius, segments, out var vertices, out var indices);
            return CreateConvexBodyWithMesh(id, position, CylinderHullPoints(cylinderHalfHeight, radius, segments), vertices, indices, color, linearVelocity);
        }

        private RapierRigidBodyComponent CreateConvexConeBody(string id, Vector3 position, float radius, Color color, Vector3 linearVelocity)
        {
            const int segments = 16;
            BuildConeMesh(radius, segments, out var vertices, out var indices);
            return CreateConvexBodyWithMesh(id, position, ConeHullPoints(radius, segments), vertices, indices, color, linearVelocity);
        }

        private RapierRigidBodyComponent CreateConvexBody(string id, Vector3 position, Vector3[] points, Color color, float visualRadius)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            ConfigureVisual(go, id, position, Quaternion.identity, Vector3.one * visualRadius * 2f, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, RapierRigidBodyType.Dynamic, Vector3.zero, Vector3.zero, 0f, 0f, false);

            var collider = go.AddComponent<RapierConvexHullCollider>();
            collider.SetPoints(points);
            collider.Density = 1f;

            go.SetActive(true);
            return body;
        }

        private RapierRigidBodyComponent CreateConvexBodyWithMesh(string id, Vector3 position, Vector3[] hullPoints, Vector3[] vertices, int[] indices, Color color, Vector3 linearVelocity)
        {
            var go = NewBodyObject(id, position, Quaternion.identity);
            AddMeshVisual(go, vertices, indices, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, RapierRigidBodyType.Dynamic, linearVelocity, Vector3.zero, 0f, 0f, false);

            var collider = go.AddComponent<RapierConvexHullCollider>();
            collider.SetPoints(hullPoints);
            collider.Density = 1f;

            go.SetActive(true);
            return body;
        }

        private RapierRigidBodyComponent CreateCompoundBody(string id, Vector3 position, float radius)
        {
            var go = NewBodyObject(id, position, Quaternion.identity);
            var core = Vector3.one * (radius * 0.5f);
            var arm = new Vector3(radius * 0.5f, radius, radius * 0.5f);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, RapierRigidBodyType.Dynamic, Vector3.zero, Vector3.zero, 0f, 0f, false);

            AddBoxCollider(go, core, Vector3.zero, 1f, 0xFFFF, 0xFFFF);
            AddBoxCollider(go, arm, new Vector3(radius, 0f, 0f), 1f, 0xFFFF, 0xFFFF);
            AddBoxCollider(go, arm, new Vector3(-radius, 0f, 0f), 1f, 0xFFFF, 0xFFFF);

            CreateBoxVisualChild(go, id + "-core", core, Vector3.zero, ColorFor("box"));
            CreateBoxVisualChild(go, id + "-arm-positive-x", arm, new Vector3(radius, 0f, 0f), ColorFor("box"));
            CreateBoxVisualChild(go, id + "-arm-negative-x", arm, new Vector3(-radius, 0f, 0f), ColorFor("box"));

            go.SetActive(true);
            return body;
        }

        private void CreateTrimeshGround(string id, Vector3[] vertices, int[] indices, Color color)
        {
            CreateTrimeshBody(id, RapierRigidBodyType.Fixed, vertices, indices, color);
        }

        private RapierRigidBodyComponent CreateTrimeshBody(string id, RapierRigidBodyType bodyType, Vector3[] vertices, int[] indices, Color color)
        {
            var go = NewBodyObject(id, Vector3.zero, Quaternion.identity);
            AddMeshVisual(go, vertices, indices, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, bodyType, Vector3.zero, Vector3.zero, 0f, 0f, false);

            var collider = go.AddComponent<RapierTrimeshCollider>();
            collider.SetGeometry(vertices, indices);
            collider.Density = 1f;

            go.SetActive(true);
            return body;
        }

        private void CreateConvexHullStatic(string id, Vector3[] hullPoints, Vector3[] vertices, int[] indices, Color color)
        {
            var go = NewBodyObject(id, Vector3.zero, Quaternion.identity);
            AddMeshVisual(go, vertices, indices, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, RapierRigidBodyType.Fixed, Vector3.zero, Vector3.zero, 0f, 0f, false);

            var collider = go.AddComponent<RapierConvexHullCollider>();
            collider.SetPoints(hullPoints);
            collider.Density = 1f;

            go.SetActive(true);
        }

        private void CreateHeightfieldGround(string id, float[] heights, int rows, int columns, Vector3 scale, Color color)
        {
            var go = NewBodyObject(id, Vector3.zero, Quaternion.identity);
            BuildHeightfieldMesh(heights, rows, columns, scale, out var vertices, out var indices);
            AddMeshVisual(go, vertices, indices, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, RapierRigidBodyType.Fixed, Vector3.zero, Vector3.zero, 0f, 0f, false);

            var collider = go.AddComponent<RapierHeightfieldCollider>();
            collider.SetHeights(heights, rows, columns, scale);
            collider.Density = 1f;

            go.SetActive(true);
        }

        private void CreateVoxelsGround(string id, Vector3[] points, Vector3 voxelSize, Color color)
        {
            var go = NewBodyObject(id, Vector3.zero, Quaternion.identity);
            BuildVoxelMesh(points, voxelSize, out var vertices, out var indices);
            AddMeshVisual(go, vertices, indices, color);

            var body = go.AddComponent<RapierRigidBodyComponent>();
            ConfigureBody(body, RapierRigidBodyType.Fixed, Vector3.zero, Vector3.zero, 0f, 0f, false);

            var collider = go.AddComponent<RapierVoxelsCollider>();
            collider.SetPoints(points, voxelSize);
            collider.Density = 1f;

            go.SetActive(true);
        }

        // ---- Component plumbing helpers ----------------------------------------------------

        private void CreateWorld(Vector3 gravity)
        {
            worldGo = new GameObject("Rapier World");
            worldGo.transform.SetParent(generatedRoot.transform, false);
            worldComponent = worldGo.AddComponent<RapierWorldComponent>();
            worldComponent.StepMode = RapierWorldStepMode.Manual;
            worldComponent.Gravity = gravity;
            worldComponent.Timestep = Mathf.Max(0.0001f, timestep);
        }

        private GameObject NewBodyObject(string id, Vector3 position, Quaternion rotation)
        {
            var go = new GameObject(id);
            go.SetActive(false);
            go.transform.SetParent(worldGo.transform, false);
            go.transform.SetPositionAndRotation(position, rotation);
            return go;
        }

        private void ConfigureVisual(GameObject go, string id, Vector3 position, Quaternion rotation, Vector3 scale, Color color)
        {
            go.name = id;
            go.SetActive(false);
            go.transform.SetParent(worldGo.transform, false);
            go.transform.SetPositionAndRotation(position, rotation);
            go.transform.localScale = scale;
            RemoveUnityCollider(go);
            SetColor(go, color);
        }

        private static void ConfigureBody(
            RapierRigidBodyComponent body,
            RapierRigidBodyType bodyType,
            Vector3 linearVelocity,
            Vector3 angularVelocity,
            float linearDamping,
            float angularDamping,
            bool ccd)
        {
            var dynamic = bodyType == RapierRigidBodyType.Dynamic;
            body.BodyType = bodyType;
            body.SyncTransformFromRapier = bodyType != RapierRigidBodyType.Fixed;
            body.CanSleep = dynamic;
            body.CcdEnabled = dynamic && ccd;
            body.InitialLinearVelocity = dynamic ? linearVelocity : Vector3.zero;
            body.InitialAngularVelocity = dynamic ? angularVelocity : Vector3.zero;
            body.LinearDamping = Mathf.Max(0f, linearDamping);
            body.AngularDamping = Mathf.Max(0f, angularDamping);
        }

        private static void AddBoxCollider(GameObject go, Vector3 halfExtents, Vector3 localPosition, float density, ushort memberships, ushort filter)
        {
            var collider = go.AddComponent<RapierBoxCollider>();
            collider.HalfExtents = halfExtents;
            collider.Density = density;
            collider.LocalPosition = localPosition;
            if (memberships != 0xFFFF || filter != 0xFFFF)
            {
                collider.SetAuthoredCollisionGroups(memberships, filter);
            }
        }

        private T AddJoint<T>(RapierRigidBodyComponent body1, RapierRigidBodyComponent body2, Vector3 anchor1, Vector3 anchor2)
            where T : RapierJointComponent
        {
            var go = new GameObject($"{typeof(T).Name}");
            go.SetActive(false);
            go.transform.SetParent(worldGo.transform, false);
            var joint = go.AddComponent<T>();
            joint.Body1 = body1;
            joint.Body2 = body2;
            joint.LocalAnchor1 = anchor1;
            joint.LocalAnchor2 = anchor2;
            return joint;
        }

        private static T GetCollider<T>(RapierRigidBodyComponent body) where T : RapierColliderComponent
        {
            return body.GetComponent<T>();
        }

        private void AddMeshVisual(GameObject go, Vector3[] vertices, int[] indices, Color color)
        {
            var mesh = new Mesh { name = go.name + "-mesh" };
            if (vertices.Length > 65000)
            {
                mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            }

            mesh.vertices = vertices;
            mesh.triangles = indices;
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();

            go.AddComponent<MeshFilter>().sharedMesh = mesh;
            go.AddComponent<MeshRenderer>().material = CreateMaterial(color);
        }

        private void CreateBoxVisualChild(GameObject parent, string id, Vector3 halfExtents, Vector3 localPosition, Color color)
        {
            var child = GameObject.CreatePrimitive(PrimitiveType.Cube);
            child.name = id;
            child.transform.SetParent(parent.transform, false);
            child.transform.localPosition = localPosition;
            child.transform.localRotation = Quaternion.identity;
            child.transform.localScale = halfExtents * 2f;
            RemoveUnityCollider(child);
            SetColor(child, color);
        }

        // ---- Geometry generation (shared with the low-level demo sample) -------------------

        private static Vector3[] CylinderHullPoints(float halfHeight, float radius, int segments)
        {
            var points = new Vector3[segments * 2];
            for (var i = 0; i < segments; i++)
            {
                var angle = Mathf.PI * 2f * i / segments;
                var x = Mathf.Cos(angle) * radius;
                var z = Mathf.Sin(angle) * radius;
                points[i] = new Vector3(x, halfHeight, z);
                points[i + segments] = new Vector3(x, -halfHeight, z);
            }

            return points;
        }

        private static Vector3[] ConeHullPoints(float radius, int segments)
        {
            var points = new Vector3[segments + 1];
            points[0] = new Vector3(0f, radius, 0f);
            for (var i = 0; i < segments; i++)
            {
                var angle = Mathf.PI * 2f * i / segments;
                points[i + 1] = new Vector3(Mathf.Cos(angle) * radius, -radius, Mathf.Sin(angle) * radius);
            }

            return points;
        }

        private static void BuildCylinderMesh(float halfHeight, float radius, int segments, out Vector3[] vertices, out int[] indices)
        {
            vertices = new Vector3[segments * 4 + 2];
            var topCenter = segments * 4;
            var bottomCenter = segments * 4 + 1;
            vertices[topCenter] = new Vector3(0f, halfHeight, 0f);
            vertices[bottomCenter] = new Vector3(0f, -halfHeight, 0f);

            for (var i = 0; i < segments; i++)
            {
                var angle = Mathf.PI * 2f * i / segments;
                var x = Mathf.Cos(angle) * radius;
                var z = Mathf.Sin(angle) * radius;
                var top = new Vector3(x, halfHeight, z);
                var bottom = new Vector3(x, -halfHeight, z);
                vertices[i] = top;
                vertices[segments + i] = bottom;
                vertices[segments * 2 + i] = top;
                vertices[segments * 3 + i] = bottom;
            }

            indices = new int[segments * 12];
            var t = 0;
            for (var i = 0; i < segments; i++)
            {
                var next = (i + 1) % segments;
                indices[t++] = i;
                indices[t++] = next;
                indices[t++] = segments + i;
                indices[t++] = next;
                indices[t++] = segments + next;
                indices[t++] = segments + i;

                indices[t++] = topCenter;
                indices[t++] = segments * 2 + next;
                indices[t++] = segments * 2 + i;

                indices[t++] = bottomCenter;
                indices[t++] = segments * 3 + i;
                indices[t++] = segments * 3 + next;
            }
        }

        private static void BuildConeMesh(float radius, int segments, out Vector3[] vertices, out int[] indices)
        {
            vertices = new Vector3[segments * 2 + 2];
            var apex = segments * 2;
            var baseCenter = segments * 2 + 1;
            vertices[apex] = new Vector3(0f, radius, 0f);
            vertices[baseCenter] = new Vector3(0f, -radius, 0f);

            for (var i = 0; i < segments; i++)
            {
                var angle = Mathf.PI * 2f * i / segments;
                var ring = new Vector3(Mathf.Cos(angle) * radius, -radius, Mathf.Sin(angle) * radius);
                vertices[i] = ring;
                vertices[segments + i] = ring;
            }

            indices = new int[segments * 6];
            var t = 0;
            for (var i = 0; i < segments; i++)
            {
                var next = (i + 1) % segments;
                indices[t++] = apex;
                indices[t++] = next;
                indices[t++] = i;

                indices[t++] = baseCenter;
                indices[t++] = segments + i;
                indices[t++] = segments + next;
            }
        }

        private static void BuildPlatformMesh(out Vector3[] vertices, out int[] indices, int subdivisions, float width, float height, float depth)
        {
            var vertexCount = subdivisions + 1;
            vertices = new Vector3[vertexCount * vertexCount];
            var elementWidth = 1f / subdivisions;
            var randomState = 0x7472696du;

            for (var row = 0; row <= subdivisions; row++)
            {
                for (var column = 0; column <= subdivisions; column++)
                {
                    var x = (column * elementWidth - 0.5f) * width;
                    var y = NextPlatformRandom(ref randomState) * height;
                    var z = (row * elementWidth - 0.5f) * depth;
                    vertices[row * vertexCount + column] = new Vector3(x, y, z);
                }
            }

            indices = new int[subdivisions * subdivisions * 6];
            var t = 0;
            for (var row = 0; row < subdivisions; row++)
            {
                for (var column = 0; column < subdivisions; column++)
                {
                    var i1 = row * vertexCount + column;
                    var i2 = row * vertexCount + column + 1;
                    var i3 = (row + 1) * vertexCount + column;
                    var i4 = (row + 1) * vertexCount + column + 1;
                    indices[t++] = i1;
                    indices[t++] = i3;
                    indices[t++] = i2;
                    indices[t++] = i3;
                    indices[t++] = i4;
                    indices[t++] = i2;
                }
            }
        }

        private static float NextPlatformRandom(ref uint state)
        {
            state = state * 1664525u + 1013904223u;
            return (state & 0x00ffffff) / 16777216f;
        }

        private static Vector3[] RandomConvexPoints(ref uint state, int count, float scale)
        {
            var points = new Vector3[count];
            for (var i = 0; i < points.Length; i++)
            {
                points[i] = new Vector3(
                    NextPlatformRandom(ref state) * scale,
                    NextPlatformRandom(ref state) * scale,
                    NextPlatformRandom(ref state) * scale);
            }

            return points;
        }

        private static Vector3[] GenerateVoxelPoints(int subdivisions)
        {
            var points = new Vector3[(subdivisions + 1) * (subdivisions + 1)];
            var index = 0;
            for (var i = 0; i <= subdivisions; i++)
            {
                for (var j = 0; j <= subdivisions; j++)
                {
                    var wave = Mathf.Sin((float)i / subdivisions * 10f) * Mathf.Cos((float)j / subdivisions * 10f);
                    var y = Mathf.Clamp(wave, -0.8f, 0.8f) * 8f;
                    points[index++] = new Vector3(i - subdivisions * 0.5f, y, j - subdivisions * 0.5f);
                }
            }

            return points;
        }

        private static void BuildVoxelMesh(Vector3[] points, Vector3 voxelSize, out Vector3[] vertices, out int[] indices)
        {
            var gridKeys = new List<Vector3Int>(points.Length);
            var seen = new HashSet<Vector3Int>();
            for (var i = 0; i < points.Length; i++)
            {
                var key = new Vector3Int(
                    Mathf.FloorToInt(points[i].x / voxelSize.x),
                    Mathf.FloorToInt(points[i].y / voxelSize.y),
                    Mathf.FloorToInt(points[i].z / voxelSize.z));
                if (seen.Add(key))
                {
                    gridKeys.Add(key);
                }
            }

            gridKeys.Sort(CompareVoxelKeys);

            var half = voxelSize * 0.5f;
            var faceOffsets = new[]
            {
                new[] { new Vector3(-half.x, -half.y, half.z), new Vector3(half.x, -half.y, half.z), new Vector3(half.x, half.y, half.z), new Vector3(-half.x, half.y, half.z) },
                new[] { new Vector3(half.x, -half.y, -half.z), new Vector3(-half.x, -half.y, -half.z), new Vector3(-half.x, half.y, -half.z), new Vector3(half.x, half.y, -half.z) },
                new[] { new Vector3(half.x, -half.y, half.z), new Vector3(half.x, -half.y, -half.z), new Vector3(half.x, half.y, -half.z), new Vector3(half.x, half.y, half.z) },
                new[] { new Vector3(-half.x, -half.y, -half.z), new Vector3(-half.x, -half.y, half.z), new Vector3(-half.x, half.y, half.z), new Vector3(-half.x, half.y, -half.z) },
                new[] { new Vector3(-half.x, half.y, half.z), new Vector3(half.x, half.y, half.z), new Vector3(half.x, half.y, -half.z), new Vector3(-half.x, half.y, -half.z) },
                new[] { new Vector3(-half.x, -half.y, -half.z), new Vector3(half.x, -half.y, -half.z), new Vector3(half.x, -half.y, half.z), new Vector3(-half.x, -half.y, half.z) }
            };

            vertices = new Vector3[gridKeys.Count * 24];
            indices = new int[gridKeys.Count * 36];
            var vertex = 0;
            var index = 0;
            for (var i = 0; i < gridKeys.Count; i++)
            {
                var center = VoxelCenter(gridKeys[i], voxelSize);
                for (var face = 0; face < faceOffsets.Length; face++)
                {
                    var baseVertex = vertex;
                    for (var corner = 0; corner < 4; corner++)
                    {
                        vertices[vertex++] = center + faceOffsets[face][corner];
                    }

                    indices[index++] = baseVertex;
                    indices[index++] = baseVertex + 1;
                    indices[index++] = baseVertex + 2;
                    indices[index++] = baseVertex;
                    indices[index++] = baseVertex + 2;
                    indices[index++] = baseVertex + 3;
                }
            }
        }

        private static int CompareVoxelKeys(Vector3Int a, Vector3Int b)
        {
            var x = a.x.CompareTo(b.x);
            if (x != 0)
            {
                return x;
            }

            var y = a.y.CompareTo(b.y);
            return y != 0 ? y : a.z.CompareTo(b.z);
        }

        private static Vector3 VoxelCenter(Vector3Int key, Vector3 voxelSize)
        {
            return new Vector3(
                (key.x + 0.5f) * voxelSize.x,
                (key.y + 0.5f) * voxelSize.y,
                (key.z + 0.5f) * voxelSize.z);
        }

        private static void BuildHeightfieldMesh(float[] heights, int rows, int columns, Vector3 scale, out Vector3[] vertices, out int[] indices)
        {
            vertices = new Vector3[rows * columns];
            for (var r = 0; r < rows; r++)
            {
                for (var c = 0; c < columns; c++)
                {
                    var x = ((float)c / (columns - 1) - 0.5f) * scale.x;
                    var z = ((float)r / (rows - 1) - 0.5f) * scale.z;
                    var y = heights[r * columns + c] * scale.y;
                    vertices[r * columns + c] = new Vector3(x, y, z);
                }
            }

            indices = BuildGridIndices(rows, columns);
        }

        private static int[] BuildGridIndices(int rows, int columns)
        {
            var indices = new int[(rows - 1) * (columns - 1) * 6];
            var t = 0;
            for (var r = 0; r < rows - 1; r++)
            {
                for (var c = 0; c < columns - 1; c++)
                {
                    var i0 = r * columns + c;
                    var i1 = r * columns + c + 1;
                    var i2 = (r + 1) * columns + c;
                    var i3 = (r + 1) * columns + c + 1;
                    indices[t++] = i0;
                    indices[t++] = i2;
                    indices[t++] = i1;
                    indices[t++] = i1;
                    indices[t++] = i2;
                    indices[t++] = i3;
                }
            }

            return indices;
        }

        // ---- Misc helpers ------------------------------------------------------------------

        private static Material CreateMaterial(Color color)
        {
            var shader = Shader.Find("Standard")
                ?? Shader.Find("Universal Render Pipeline/Lit")
                ?? Shader.Find("Sprites/Default");
            return new Material(shader) { color = color };
        }

        private string NextId(string prefix)
        {
            nextBodyId++;
            return $"{prefix}-{nextBodyId:0000}";
        }

        private static int IndexOf(DemoKind value)
        {
            for (var i = 0; i < DemoValues.Length; i++)
            {
                if (DemoValues[i] == value)
                {
                    return i;
                }
            }

            return 0;
        }

        private static Color ColorFor(string role)
        {
            switch (role)
            {
                case "floor":
                    return new Color(0.28f, 0.32f, 0.36f);
                case "sphere":
                    return new Color(0.16f, 0.52f, 0.92f);
                case "capsule":
                    return new Color(0.37f, 0.73f, 0.38f);
                case "keva":
                    return new Color(0.86f, 0.63f, 0.35f);
                default:
                    return new Color(0.95f, 0.55f, 0.18f);
            }
        }

        private void EnsureCameraAndLight()
        {
            var camera = Camera.main;
            if (camera == null)
            {
                var cameraObject = new GameObject("Rapier Demo Camera");
                cameraObject.transform.SetParent(generatedRoot.transform, false);
                camera = cameraObject.AddComponent<Camera>();
                cameraObject.tag = "MainCamera";
            }

            if (UnityEngine.Object.FindObjectOfType<Light>() == null)
            {
                var lightObject = new GameObject("Rapier Demo Light");
                lightObject.transform.SetParent(generatedRoot.transform, false);
                var light = lightObject.AddComponent<Light>();
                light.type = LightType.Directional;
                light.intensity = 1.1f;
                lightObject.transform.rotation = Quaternion.Euler(50f, -30f, 0f);
            }
        }

        private static void LookAt(Vector3 eye, Vector3 target)
        {
            var camera = Camera.main;
            if (camera == null)
            {
                return;
            }

            camera.transform.position = eye;
            camera.transform.LookAt(target);
            camera.nearClipPlane = 0.01f;
            camera.farClipPlane = 500f;
        }

        private static bool TryProbeNative(out string error)
        {
            try
            {
                using (var probe = RapierWorld.Create())
                {
                    probe.SetGravity(Vector3.zero);
                    probe.SetTimestep(1f / 60f);
                }

                error = null;
                return true;
            }
            catch (Exception ex) when (IsNativeFailure(ex))
            {
                error = "Rapier native plugin is not available. Build and copy rapier_unity_ffi for this platform.";
                return false;
            }
        }

        private static bool IsNativeFailure(Exception ex)
        {
            return ex is DllNotFoundException
                || ex is EntryPointNotFoundException
                || ex is BadImageFormatException
                || ex is InvalidOperationException;
        }

        private static bool IsNativeLoadFailure(Exception ex)
        {
            return ex is DllNotFoundException
                || ex is EntryPointNotFoundException
                || ex is BadImageFormatException;
        }

        private static void RemoveUnityCollider(GameObject gameObject)
        {
            var unityCollider = gameObject.GetComponent<Collider>();
            if (unityCollider != null)
            {
                UnityEngine.Object.Destroy(unityCollider);
            }
        }

        private static void SetColor(GameObject gameObject, Color color)
        {
            var renderer = gameObject.GetComponent<MeshRenderer>();
            if (renderer != null)
            {
                renderer.material.color = color;
            }
        }

        private void DestroyGeneratedRoot()
        {
            if (generatedRoot != null)
            {
                Destroy(generatedRoot);
                generatedRoot = null;
            }

            worldGo = null;
            worldComponent = null;
        }
    }
}
